import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const watch = (process.argv[2] === 'watch');

// Inline-Plugin - korrigierte Version
const inlinePlugin = {
    name: 'inline',
    setup(build) {
        // Lade die Datei für inline:-Importe
        build.onResolve({ filter: /^inline:/ }, (args) => {
            const filePath = args.path.replace(/^inline:/, '');
            const resolvedPath = path.resolve(args.resolveDir, filePath);
            return {
                path: resolvedPath,
                namespace: 'inline',
            };
        });

        build.onLoad({ filter: /.*/, namespace: 'inline' }, async (args) => {
            const contents = await fs.promises.readFile(args.path, 'utf8');
            return {
                contents,
                loader: 'text',
                resolveDir: path.dirname(args.path),
            };
        });
    },
};

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ['main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/closebrackets',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/comment',
        '@codemirror/fold',
        '@codemirror/gutter',
        '@codemirror/highlight',
        '@codemirror/history',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/matchbrackets',
        '@codemirror/panel',
        '@codemirror/rangeset',
        '@codemirror/rectangular-selection',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/stream-parser',
        '@codemirror/text',
        '@codemirror/tooltip',
        '@codemirror/view',
        ...builtins
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outdir: 'build',
    plugins: [inlinePlugin],
    platform: 'browser',
};

// Watch- oder einmaligen Build ausführen
if (watch) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    console.log('👀 Watching for changes...');
} else {
    esbuild.build(buildOptions).catch(() => process.exit(1));
}
